### Cadastrar um novo usuário
POST https://localhost:5001/api/usuario/create
Content-Type: application/json

{
    "Email" : "mario@hotmail.com",
    "Senha" : "123"
}

### Listar usuários
GET https://localhost:5001/api/usuario/list
Content-Type: application/json

### Get by id
GET https://localhost:5001/api/usuario/getbyid/1
Content-Type: application/json


### Realizar o login
GET https://localhost:5001/api/usuario/login
Content-Type: application/json

{
    "Email" : "leo@hotmail.com",
    "Senha" : "123"
}

### Realizar o Logout
GET https://localhost:5001/api/usuario/logout
Content-Type: application/json

{
    "Email" : "leo@hotmail.com"
}